name: Telemetry Automation
on:
  push:
    branches: [ "tryactions" ]

jobs:
  tests:
    runs-on: ubuntu-latest
  
    steps:
        
    - name: Checkout code
      uses: actions/checkout@v3         
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
            python-version: '3.11'  # Choose your desired Python version
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: automation
        tags: |
          type=ref,event=branch
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./automate/Docker_local
        push: false
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        
    - name: Set up Docker Compose
      run: |
        docker compose -f ./automate/docker_compose.yaml up -d

    - name: Set up Docker Compose
      run: ls -l  ./automate

    - name: Run the docker
      run: |
        docker run -e CONDITION1=true  ${{ steps.meta.outputs.tags }}
        docker-compose exec robot /bin/bash
      continue-on-error: true

    - name: Set up Docker Compose
      run: ls -l  ./automate

    - name: Set up Docker Compose
      run: :|
        ls  -l  ./results 

    - name: Upload Dist
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ./results

    - name: Download artifact
      uses: actions/download-artifact@v3
      id: download
      with:
        name: reports
        path: ./reports       
      
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.3
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          reports/res.xml

    - name: Test Summary
      uses: test-summary/action@v2
      with:
          paths: reports/res.xml
          output: test-summary.md
      if: always()
    - name: display the test summary
      run: |
        cat test-summary.md


  
